{% set name = "SPIRV-Tools" %}
{% set version = "2026.1" %}
# Keep this in synch with spirv-headers https://github.com/KhronosGroup/SPIRV-Tools/blob/v2026.1/DEPS#L17 ->
# spirv_headers_revision': '04f10f650d514df88b76d25e83db360142c7b174 -> 
# https://github.com/KhronosGroup/SPIRV-Headers/commit/04f10f650d514df88b76d25e83db360142c7b174 ->
# https://github.com/KhronosGroup/SPIRV-Headers/releases/tag/vulkan-sdk-1.4.341.0
{% set headers_version = "1.4.341.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/KhronosGroup/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 35dc16cf2dc64be5b6bbbe86d210e6f4a82b070cffd751605a3365cd8bce2d7e

build:
  run_exports:
    # They seem to be using calver, so their version numbers are not very informative
    # But we expect these to be rather stable
    # so lets try 'x' https://github.com/conda-forge/spirv-tools-feedstock/issues/3
    - {{ pin_subpackage('spirv-tools', 'x') }}
  number: 0

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make    # [unix]
    - ninja-base   # [win]
    - python
  host:
    - spirv-headers {{ headers_version }}
  run_constrained:
    - {{ pin_compatible('spirv-headers', max_pin='x.x.x.x') }}

test:
  commands:
    - spirv-as -h

about:
  home: https://github.com/KhronosGroup/SPIRV-Tools
  dev_url: https://github.com/KhronosGroup/SPIRV-Tools
  doc_url: https://github.com/KhronosGroup/SPIRV-Tools
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: The SPIR-V Tools project provides an API and commands for processing SPIR-V modules.
  description: The SPIR-V Tools project provides an API and commands for processing SPIR-V modules.

extra:
  recipe-maintainers:
    - oleksandr-pavlyk
    - ZzEeKkAa
    - isuruf
    - hmaarrfk
